name: trackcovid
description: COVID Tracker

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fancy_bottom_navigation: ^0.3.2
  http: ^0.12.1
  url_launcher: ^5.4.10
  get_it: ^4.0.2
  flutter_open_whatsapp: ^0.1.2
  flutter_phone_state: ^0.5.9
  rflutter_alert: ^1.0.3
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1
  flutter_local_notifications: ^1.4.4+1
  path_provider: ^1.6.11
  rxdart: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/virus.png"
  android: "launcher_icon"
  ios: true

flutter_launcher_name:
  name: "COVID Info"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - images/

  fonts:
    - family: MyCustomIcons
      fonts:
        - asset: assets/fonts/MyApp.ttf
